use_frameworks!

inhibit_all_warnings!

platform :ios, '9.0'

target 'SmartWKWebView_Example' do
  pod 'SmartWKWebView', :path => '../'

  target 'SmartWKWebView_Tests' do
    inherit! :search_paths
  end
end
